#APPLICATION BROWSER
browser=chrome
#APPLICATION URL
url=https://www.demoblaze.com/
#APPLICATION USERNAME AND PASSWORD
username=test.bidishaw
password=test@123
screenshots=.//Screenshot/
location=.//Screenshot//
name=Bidishaw
country=India
city=Chennai
credit=14894577984
month=09
year=2026